[phases.setup]
nixPkgs = ["nodePackages.npm", "python311", "python311Packages.pip"]

[phases.install]
cmds = ["npm install", "pip install -r requirements.txt"]

[phases.build]
cmds = ["echo Building..."]

[start]
cmd = "npm start"
